import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import ts from 'typescript';
import {createRequire} from 'node:module';
import {memoryDatabase,runtimeDDL} from '../scripts/check-db-schema.mjs';
import {mobileIntakeHarness} from './helpers/mobile-intake.mjs';
const native=createRequire(import.meta.url),plain=value=>JSON.parse(JSON.stringify(value));
const nodes=value=>Array.isArray(value)?value.flatMap(nodes):value&&typeof value==='object'?[value,...nodes(value.props?.children)]:[];
const text=value=>Array.isArray(value)?value.map(text).join(''):value&&typeof value==='object'?text(value.props?.children):value==null?'':String(value);
const companies=[{id:'local-yun',code:'A01526306',name:'유앤채',email:'jwhj1116@kakao.com',role:'admin'},{id:'local-waih',code:'A01464742',name:'와이홉',email:'unari8484@gmail.com',role:'member'}];
const json=async(response,status=200)=>{assert.equal(response.status,status,await response.clone().text());return response.json();};
function modules(deps={},extra={}){const cache=new Map();function load(file){if(cache.has(file))return cache.get(file);const exports={};cache.set(file,exports);vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,Error,URL,Request,Response,Headers,TextEncoder,TextDecoder,Uint8Array,DataView,structuredClone,crypto,...extra,require(name){if(name in deps)return deps[name];if(name.startsWith('./')||name.startsWith('../'))return load(path.posix.join(path.posix.dirname(file),name)+'.ts');const source=name.slice(2);return name.startsWith('@/')?load(source+(source.includes('/components/')?'.tsx':'.ts')):native(name);}});return exports;}return load;}

test('fresh/legacy settings keep integration off until a confirmed rate is supplied; inactive settings fingerprints remain unchanged',()=>{
 const load=modules(),settings=load('app/workspace-settings.ts'),fingerprint=load('app/settings-fingerprint.ts').savedProductFingerprintSettings;
 for(const value of [settings.defaultSettings,settings.newWorkspaceSettings,settings.validateSettings({}),settings.savedRegistrationSettings(null)]){assert.equal(value.useIntegratedRate,false);assert.equal(value.integratedRate,null);}
 const legacy={...settings.defaultSettings};delete legacy.useIntegratedRate;delete legacy.integratedRate;const normalized=settings.validateSettings(legacy);assert.equal(JSON.stringify(fingerprint(legacy)),JSON.stringify(fingerprint(normalized)));assert.equal(JSON.stringify(fingerprint({...normalized,integratedRate:450})),JSON.stringify(fingerprint(legacy)));
 const active=settings.validateSettings({...normalized,useIntegratedRate:true,integratedRate:350});assert.notEqual(JSON.stringify(fingerprint(active)),JSON.stringify(fingerprint(normalized)));assert.notEqual(JSON.stringify(fingerprint({...active,integratedRate:351})),JSON.stringify(fingerprint(active)));
 for(const rate of [null,undefined,'350',0,-1,NaN,Infinity])assert.throws(()=>settings.validateSettings({...normalized,useIntegratedRate:true,integratedRate:rate}));
 const preset=load('app/observed-price-preset.ts').applyObservedPricePreset(active);assert.equal(preset.useIntegratedRate,false);assert.equal(preset.integratedRate,350);assert.equal(preset.brand,active.brand);
});

test('legacy and disabled captured intake settings have no false drift, while an active flag or rate change is reported without rewriting the capture',()=>{
 const load=modules(),settings=load('app/workspace-settings.ts'),source=load('app/sourcing.ts'),compare=load('app/collection-preservation.ts').preservedCollectionRequests,legacy={...settings.newWorkspaceSettings};delete legacy.useIntegratedRate;delete legacy.integratedRate;
 const context={category:{id:'cat',name:'검토 분류',categoryId:'80719',categoryPath:['주방'],revision:1,mappings:[],template:null},settings:legacy,features:'',keywords:'',capturedAt:'2026-10-07T00:00:00.000Z'},requests=source.parseCollectionRequest({urls:['https://detail.1688.com/offer/813724060928.html'],goal:'price'}),jobs=[{id:'job',offer_id:requests[0].offerId,source_url:requests[0].sourceUrl,goal:'price',status:'awaiting_connector',context}],before=JSON.stringify(jobs);
 for(const rate of [null,350,450])assert.deepEqual(plain(compare(jobs,requests,{...context,settings:{...legacy,useIntegratedRate:false,integratedRate:rate}})),[]);
 const enabled={...context,settings:{...legacy,useIntegratedRate:true,integratedRate:350}};assert.deepEqual(plain(compare(jobs,requests,enabled)[0].differences),['기본설정']);const activeJobs=[{...jobs[0],context:enabled}];assert.deepEqual(plain(compare(activeJobs,requests,{...enabled,settings:{...enabled.settings,integratedRate:351}})[0].differences),['기본설정']);assert.equal(JSON.stringify(jobs),before);
});

function settingsAPI(){
 const sqlite=memoryDatabase();for(const declaration of runtimeDDL())sqlite.exec(declaration.sql);let account=companies[0];const state={external:0};
 const db={prepare(sql){let args=[];const q={bind(...values){args=values;return q;},execute(){return sqlite.prepare(sql).all(...args);},async first(){return q.execute()[0]??null;},async all(){return{results:q.execute()};},async run(){return sqlite.prepare(sql).run(...args);}};return q;},async batch(statements){sqlite.exec('BEGIN');try{const rows=statements.map(q=>({results:q.execute()}));sqlite.exec('COMMIT');return rows;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
 const load=modules({'cloudflare:workers':{env:{DB:db,YOOFAM_AUTH_ENABLED:'true'}},'next/server':{NextResponse:Response},'@/app/chatgpt-auth':{getChatGPTUser:async()=>({verifiedAccess:true,userId:account.id,email:account.email,membership:{id:account.id,email:account.email,role:account.role,status:'approved',companyCode:account.code,companyName:account.name}}),getWorkspaceOwnerId:async()=>account.id}},{process:{env:{NODE_ENV:'production'}},fetch(){state.external++;throw Error('settings must not call a rate provider');}}),route=load('app/api/settings/route.ts');
 return{sqlite,load,state,login(value){account=value;},get:()=>route.GET(),put:body=>route.PUT(new Request('https://app.test/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)})),snapshot:()=>JSON.stringify(sqlite.prepare('SELECT * FROM workspace_settings ORDER BY owner_id').all()),close(){sqlite.close();}};
}

test('two native members save separate confirmed rates and a stale expected owner cannot change the other account',async()=>{
 const h=settingsAPI();try{const settings=h.load('app/workspace-settings.ts').newWorkspaceSettings;for(const [index,company]of companies.entries()){h.login(company);assert.equal((await json(await h.get())).settings,null);const saved=await json(await h.put({...settings,expectedOwnerId:company.id,brand:company.name,useIntegratedRate:true,integratedRate:300+index*50}));assert.equal(saved.settings.integratedRate,300+index*50);assert.deepEqual(saved.scope,{ownerId:company.id,company:{code:company.code,name:company.name}});}
  const before=h.snapshot();h.login(companies[1]);await json(await h.put({...settings,expectedOwnerId:companies[0].id,useIntegratedRate:true,integratedRate:999}),409);await json(await h.put({...settings,expectedOwnerId:companies[1].id,useIntegratedRate:true,integratedRate:null}),400);assert.equal(h.snapshot(),before);
  for(const[index,company]of companies.entries()){h.login(company);const read=await json(await h.get());assert.equal(read.settings.brand,company.name);assert.equal(read.settings.integratedRate,300+index*50);}
  assert.equal(h.state.external,0);
 }finally{h.close();}
});

// Real intake/option/quotation routes and private SQLite; recorded source, AI,
// images and authentication are fixtures. Nothing is submitted to Supplier Hub.
for(const company of companies)test(`captured integrated rate remains attached to newly sourced product and per-SKU manual quote values (${company.code})`,async()=>{
 const api=mobileIntakeHarness({companyCode:company.code,companyName:company.name});try{
  api.context.settings={...api.context.settings,useIntegratedRate:true,integratedRate:280,minimumMarginEnabled:false,minimumMargin:0,bundleEnabled:false};api.sqlite.prepare('UPDATE collection_context SET payload=? WHERE job_id=?').run(JSON.stringify(api.context),'job');const capture=api.sqlite.prepare('SELECT payload FROM collection_context').get().payload;
  await api.load('db/queries.ts').saveSettings('owner',JSON.stringify({...api.context.settings,integratedRate:400}));await api.intake();const product=api.sqlite.prepare('SELECT * FROM products').get(),stored=JSON.parse(api.sqlite.prepare('SELECT payload FROM product_price_policy').get().payload);assert.equal(stored.useIntegratedRate,true);assert.equal(stored.integratedRate,280);const base='/api/products/'+product.id,options=await json(await api.route(base+'/options'));assert.equal(options.pricing.policy.integratedRate,280);assert.equal(options.pricing.policySource,'saved-product');assert.equal(options.pricing.rows[0].calculation.costKrw,Math.round((options.options.rows[0].unitCostCny*options.options.rows[0].unitsPerPack*280+300)*1.1));
  let q=await json(await api.route(base+'/quotation-fields'));const target=q.resolved.rows.find(row=>row.optionId),other=q.resolved.rows.filter(row=>row.optionId)[1],otherBefore=plain(other.fields);q=await json(await api.route(base+'/quotation-fields',{method:'PUT',body:{expectedRevision:q.revision,expectedInputFingerprint:q.inputFingerprint,changes:[{optionId:target.optionId,fieldKey:'supplyPrice',value:'12345'},{optionId:target.optionId,fieldKey:'msrp',value:''}]}}));const manual=q.resolved.rows.find(row=>row.optionId===target.optionId);assert.equal(manual.fields.supplyPrice.value,'12345');assert.equal(manual.fields.msrp.value,'');assert.deepEqual(plain(q.resolved.rows.find(row=>row.optionId===other.optionId).fields),otherBefore);assert.equal(api.sqlite.prepare('SELECT payload FROM collection_context').get().payload,capture);assert.equal(JSON.parse(api.sqlite.prepare('SELECT payload FROM product_price_policy').get().payload).integratedRate,280);assert.equal(api.sqlite.prepare('SELECT supplier_hub_status FROM products').get().supplier_hub_status,'미전송');assert.ok(!api.network.some(host=>/couplus|exchange|currency/.test(host)));
 }finally{api.close();}
});

function ui(kind,initialOverride={}){
 const instances=new Map(),saves=[],cache=new Map();let active,changed=false,closed=0,external=0;
 const hooks={useState(initial){const i=active.index++,owner=active;if(!(i in owner.slots))owner.slots[i]=typeof initial==='function'?initial():initial;return[owner.slots[i],value=>{const next=typeof value==='function'?value(owner.slots[i]):value;if(!Object.is(owner.slots[i],next))changed=true;owner.slots[i]=next;}];},useRef(initial){const i=active.index++;return active.slots[i]??(active.slots[i]={current:initial});}};
 function load(file){if(cache.has(file))return cache.get(file);const exports={};cache.set(file,exports);vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,Error,fetch(){external++;throw Error('UI must not fetch a rate or autosave');},require(name){if(name==='react')return hooks;if(name==='react/jsx-runtime')return{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};if(name==='@/app/components/option-quotation-prices')return{OptionQuotationPrices:()=>null};if(name==='@/app/components/option-price-preview')return{OptionPricePreview:()=>null};if(name.startsWith('./')||name.startsWith('../'))return load(path.posix.join(path.posix.dirname(file),name)+'.ts');const target=name.slice(2);return name.startsWith('@/')?load(target+(target.includes('/components/')?'.tsx':'.ts')):native(name);}});return exports;}
 let initial={...(kind==='settings'?load('app/workspace-settings.ts').newWorkspaceSettings:{exchangeRate:200,supplyMargin:50,coupangMargin:40,minimumMargin:0,msrpMultiple:1.3,roundingUnit:10,roundingMode:'nearest'}),...initialOverride};
 const Component=kind==='settings'?load('app/components/workspace-settings-editor.tsx').WorkspaceSettingsEditor:load('app/components/price-editor.tsx').PriceEditor;
 function expand(tree){if(Array.isArray(tree))return tree.map(expand);if(!tree||typeof tree!=='object')return tree;if(typeof tree.type==='function'){const instance=instances.get(tree.type)??{slots:[]};instances.set(tree.type,instance);instance.index=0;active=instance;return expand(tree.type(tree.props));}return{...tree,props:{...tree.props,children:expand(tree.props?.children)}};}
 const render=()=>{for(let i=0;i<10;i++){changed=false;const props=kind==='settings'?{value:initial,onSave:async value=>saves.push(plain(value)),onClose:()=>closed++}:{initial,sourcePrice:5.23,onSave:async value=>{saves.push(plain(value));initial={...value};}};const tree=expand({type:Component,props});if(!changed)return tree;}throw Error('pricing UI render loop');};
 const control=label=>{const all=nodes(render()),named=all.find(node=>node.props?.['aria-label']===label);if(named)return named;const parent=all.find(node=>node.type==='label'&&text(Array.isArray(node.props.children)?node.props.children[0]:node.props.children)===label);return nodes(parent).find(node=>['input','select','textarea'].includes(node.type));};
 return{render,saves,control,load,get external(){return external;},get closed(){return closed;},get initial(){return initial;},update(value){initial=value;},edit(label,value){const target=control(label);assert.ok(target&&!target.props.disabled,'pricing control '+label);target.props.onChange({target:typeof value==='boolean'?{checked:value}:{value:String(value)}});},button:label=>nodes(render()).find(node=>node.type==='button'&&text(node)===label),save:()=>render().props.onSubmit({preventDefault(){}})};
}

test('workspace integration toggle keeps a blank rate invalid, retains edited fields across parent changes and saves only by explicit submission',async()=>{
 const h=ui('settings'),before=JSON.stringify(h.initial);h.edit('통합통관 환율 사용',true);assert.equal(h.control('통합통관 적용환율 (CNY → KRW)').props.value,'');assert.equal(h.control('적용환율 (CNY → KRW)'),undefined);await h.save();assert.equal(h.saves.length,0);assert.ok(nodes(h.render()).some(node=>node.props?.role==='alert'));h.edit('통합통관 적용환율 (CNY → KRW)',350);h.edit('미리보기 원가 (CNY)',3.6);const preview=nodes(h.render()).find(node=>node.props?.['aria-label']==='기본 가격 미리보기');assert.ok(text(preview).includes('4,720원'));assert.equal(h.saves.length,0);h.update({...h.initial,useIntegratedRate:true,integratedRate:450});assert.equal(h.control('통합통관 적용환율 (CNY → KRW)').props.value,'350');h.edit('통합통관 환율 사용',false);assert.equal(h.control('적용환율 (CNY → KRW)').props.value,'350');h.edit('통합통관 환율 사용',true);assert.equal(h.control('통합통관 적용환율 (CNY → KRW)').props.value,'350');await h.save();assert.equal(h.saves.length,1);assert.equal(h.saves[0].useIntegratedRate,true);assert.equal(h.saves[0].integratedRate,350);assert.equal(h.external,0);assert.notEqual(JSON.stringify(h.initial),before,'only the supplied parent value was deliberately changed by this test');
});

test('PriceEditor treats active flag/rate as dirty, blocks a missing rate and preserves it until an explicit reload or save',async()=>{
 const h=ui('price');h.edit('통합통관 환율 사용',true);assert.equal(h.render().props['data-workspace-dirty'],true);assert.equal(h.control('통합통관 적용환율 (CNY → KRW)').props.value,'');await h.save();assert.equal(h.saves.length,0);h.edit('통합통관 적용환율 (CNY → KRW)',350);assert.match(text(h.render()),/2,344원/);assert.match(text(h.render()),/4,690원/);const next={...h.initial,useIntegratedRate:true,integratedRate:500};h.update(next);assert.equal(h.control('통합통관 적용환율 (CNY → KRW)').props.value,350);assert.match(text(h.render()),/수정 중인 입력은 유지/);assert.equal(h.saves.length,0);h.button('수정 취소·최신 가격 정책 불러오기').props.onClick();assert.equal(h.control('통합통관 적용환율 (CNY → KRW)').props.value,500);assert.equal(h.render().props['data-workspace-dirty'],false);h.edit('통합통관 적용환율 (CNY → KRW)',350);await h.save();assert.equal(h.saves.length,1);assert.equal(h.saves[0].integratedRate,350);assert.equal(h.render().props['data-workspace-dirty'],false);assert.equal(h.external,0);
});
