import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import path from 'node:path';
import {createRequire} from 'node:module';
import {mobileIntakeHarness} from './helpers/mobile-intake.mjs';
import {quotationWorkbook} from './helpers/quotation-workbook.mjs';
const native=createRequire(import.meta.url),plain=value=>JSON.parse(JSON.stringify(value));
const nodes=value=>Array.isArray(value)?value.flatMap(nodes):value&&typeof value==='object'?[value,...nodes(value.props?.children)]:[];
const text=value=>Array.isArray(value)?value.map(text).join(''):value&&typeof value==='object'?text(value.props?.children):value==null?'':String(value);
const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return{promise,resolve};};
const initialVersion='2026-10-07T00:00:00.000Z',advance=value=>new Date(Date.parse(value)+1).toISOString();
const json=async response=>{assert.equal(response.status,200,await response.clone().text());return response.json();};

function imageUI(fetcher,{productId='p',optionId='red',version=initialVersion,profileId,refreshToken='0',stage='additional',disabled=false}={}){
 const slots=[],effects=[],layouts=[],cache=new Map(),calls=[];let cursor=0,saved=0,closed=false,lateWrites=0,saveVersion,stateEpoch=0;
 const effect=(queue,fn,deps)=>{const i=cursor++;if(!slots[i]||JSON.stringify(slots[i].deps)!==JSON.stringify(deps)){const previous=slots[i],next={deps,cleanup:previous?.cleanup};slots[i]=next;queue.push(()=>{previous?.cleanup?.();next.cleanup=fn();});}};
 const react={useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],value=>{if(closed){lateWrites++;return;}stateEpoch++;slots[i]=typeof value==='function'?value(slots[i]):value;}];},useRef(initial){const i=cursor++;return slots[i]??(slots[i]={current:initial});},useEffect(fn,deps){effect(effects,fn,deps);},useLayoutEffect(fn,deps){effect(layouts,fn,deps);}};
 function load(file){if(cache.has(file))return cache.get(file);const exports={};cache.set(file,exports);vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,Error,AbortController,structuredClone,TextEncoder,fetch:async(url,init)=>{calls.push({url,init});const response=await fetcher(url,init);if(init?.method==='PUT'&&response.ok)saveVersion=(await response.clone().json()).productVersion;return response;},require(name){if(name==='react')return react;if(name==='react/jsx-runtime')return{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};if(name.startsWith('./')||name.startsWith('../'))return load(path.posix.join(path.posix.dirname(file),name)+'.ts');return name.startsWith('@/')?load(name.slice(2)+'.ts'):native(name);}});return exports;}
 const Component=load('app/components/option-image-editor.tsx').OptionImageEditor;
 const render=(flush=true)=>{cursor=0;const tree=Component({productId,optionId,version,profileId,refreshToken,stage,disabled,onSaved(){saved++;stateEpoch++;version=saveVersion;}});layouts.splice(0).forEach(fn=>fn());if(flush)effects.splice(0).forEach(fn=>fn());return tree;};
 // Two unchanged commit/event-loop turns include the host's post-ACK version
 // refresh and its newly scheduled GET, rather than observing busy=false once.
 const idle=async()=>{let quiet=0;const deadline=Date.now()+10000;for(;;){const epoch=stateEpoch,count=calls.length,currentVersion=version;render();await new Promise(resolve=>setImmediate(resolve));render();await Promise.resolve();const tree=render();if(!tree.props['data-workspace-saving']&&epoch===stateEpoch&&count===calls.length&&currentVersion===version&&!effects.length&&!layouts.length)quiet++;else quiet=0;if(quiet===2)return;assert.ok(Date.now()<deadline,'option image UI request timed out');await new Promise(resolve=>setTimeout(resolve,1));}};
 const control=label=>nodes(render()).find(node=>node.props?.['aria-label']===label),button=label=>nodes(render()).find(node=>node.type==='button'&&(node.props['aria-label']===label||text(node)===label));
 render();return{render,load,calls,control,button,idle,get saved(){return saved;},get lateWrites(){return lateWrites;},stage(value){stage=value;render();},source(value,nextRefresh=refreshToken,flush=true){version=value;refreshToken=nextRefresh;render(flush);},select(value){optionId=value;render();},close(){closed=true;slots.forEach(slot=>slot?.cleanup?.());},async click(label){const target=button(label);assert.ok(target&&!target.props.disabled,'available image button '+label+' '+text(render()));target.props.onClick();await idle();},choose(label){const target=control(label);assert.ok(target&&!target.props.disabled,'available image candidate '+label);target.props.onChange();},html(value){control('선택 옵션 상세 HTML').props.onChange({target:{value}});}};
}

function fixture(){
 const keys=['owner/one.png','owner/two.png','owner/three.png','owner/four.png'];
 const paths={additionalImages:['imagePage','images','additionalImage'],detailImages:['imagePage','details','detailedImage'],detailHtml:['imagePage','details','htmlProductDetailContent']};
 const canonical=Object.keys(paths).map(id=>({id,label:id,type:id==='detailHtml'?'textarea':'images',section:'image',required:false,visibility:'common',maxLength:id==='detailHtml'?150000:16000,...(id==='detailHtml'?{}:{maxItems:30})}));
 const fields=[...canonical,...canonical.map(field=>({...field,id:'wire-'+field.id,hubInput:field.id,hubWire:{path:paths[field.id]}}))];
 const overrides={common:{additionalImages:keys[0],'wire-additionalImages':keys[1],detailImages:keys[1],'wire-detailImages':keys[2],detailHtml:'<p>공통 상세</p>','wire-detailHtml':'<p>공통 Hub 상세</p>'},options:{red:{unrelated:'보존'},blue:{additionalImages:keys[3],'wire-additionalImages':keys[3],detailImages:keys[3],'wire-detailImages':keys[3],detailHtml:'<p>다른 옵션 HTML</p>','wire-detailHtml':'<p>다른 옵션 HTML</p>'}}};
 const rows=values=>['red','blue'].map(optionId=>({optionId,optionLabel:optionId,included:true,fields:Object.fromEntries(fields.map(field=>{const own=values.options[optionId]??{},hasOwn=Object.hasOwn(own,field.id),hasCommon=Object.hasOwn(values.common,field.id);return[field.id,{value:hasOwn?own[field.id]:hasCommon?values.common[field.id]:field.type==='images'?keys[0]:'<p>자동 상세</p>',source:hasOwn?'manual-option':hasCommon?'manual-common':'content',validationIssues:[]}];}))}));
 const view={revision:1,inputFingerprint:'a'.repeat(64),productVersion:initialVersion,updatedAt:initialVersion,contentRevision:2,optionRevision:3,imageKeys:keys,categoryContext:{categoryId:'80719',categoryPath:['주방'],profileId:null},overrides,resolved:{schema:{fields},rows:rows(overrides)},automatic:{schema:{fields},rows:rows({common:{},options:{}})}};
 return{keys,view,reply(url,init){if(init?.method==='PUT'){const body=JSON.parse(init.body);if(body.expectedRevision!==view.revision)return Response.json({error:'동시 이미지 수정'},{status:409});for(const change of body.changes){const own=view.overrides.options[change.optionId]??={};if(change.value===null)delete own[change.fieldKey];else own[change.fieldKey]=change.value;if(!Object.keys(own).length)delete view.overrides.options[change.optionId];}view.revision++;view.productVersion=advance(view.productVersion);view.updatedAt=view.productVersion;view.resolved.rows=rows(view.overrides);}return Response.json(view);}};
}

test('image and HTML targets require exact primary paths, preserve canonical fallbacks and reject ambiguity or wrong types',()=>{
 const h=imageUI(()=>Response.json(fixture().view));try{const model=h.load('app/quotation-image-targets.ts'),f=fixture();assert.equal(model.optionImageTargets(f.view.resolved.schema.fields).detailHtml.primary,'wire-detailHtml');assert.deepEqual(plain(model.optionImageTargets(f.view.resolved.schema.fields).additionalImages.linked),['additionalImages','wire-additionalImages']);
  const fallback=f.view.resolved.schema.fields.filter(field=>!field.id.startsWith('wire-'));assert.equal(model.optionImageTargets(fallback).detailHtml.primary,'detailHtml');
  for(const bad of [[...f.view.resolved.schema.fields,{...f.view.resolved.schema.fields.at(-1),id:'duplicate'}],f.view.resolved.schema.fields.map(field=>field.id==='wire-detailHtml'?{...field,hubInput:undefined}:field),f.view.resolved.schema.fields.map(field=>field.id==='wire-detailImages'?{...field,type:'textarea'}:field)])assert.throws(()=>model.optionImageTargets(bad));
  assert.throws(()=>model.optionImageChanges(f.view,'red',{additionalImages:'other-owner/photo.png'}),/이미지 참조/);assert.throws(()=>model.optionImageChanges(f.view,'red',{detailImages:f.keys[0]+'\n'+f.keys[0]}),/이미지 참조/);
 }finally{h.close();}
});

test('candidate preview, ordered choices, removals, explicit blanks and reset affect only the selected additional-image fields',async()=>{
 const f=fixture(),before=plain(f.view.overrides),h=imageUI((url,init)=>f.reply(url,init));try{await h.idle();assert.equal(h.calls.some(call=>call.init?.method==='PUT'),false);const workspace=nodes(h.render()).find(node=>node.props?.className==='image-edit-workspace');assert.equal(workspace.props.children[0].type,'aside');assert.equal(workspace.props.children[1].type,'section');assert.equal(h.control('선택 옵션 추가 이미지 후보 2').props.checked,true);
  await h.click('상품 저장 이미지 3 크게 보기');assert.equal(nodes(h.render()).find(node=>node.type==='img'&&node.props.alt==='선택 옵션 추가 이미지 큰 미리보기').props.src,'/api/files/owner/three.png');assert.equal(h.calls.some(call=>call.init?.method==='PUT'),false);
  h.choose('선택 옵션 추가 이미지 후보 3');await h.click('추가 이미지 2 위로 이동');await h.click('추가 이미지 2 선택 제거');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,1,text(h.render()));const put=JSON.parse(h.calls.find(call=>call.init?.method==='PUT').init.body);assert.deepEqual(put.changes,[{fieldKey:'additionalImages',optionId:'red',value:f.keys[2]},{fieldKey:'wire-additionalImages',optionId:'red',value:f.keys[2]}]);assert.deepEqual(f.view.overrides.common,before.common);assert.deepEqual(f.view.overrides.options.blue,before.options.blue);assert.equal(f.view.overrides.options.red.unrelated,'보존');assert.equal(Object.hasOwn(f.view.overrides.options.red,'detailHtml'),false);
  await h.click('추가 이미지 선택 비우기');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,2,text(h.render()));assert.equal(f.view.overrides.options.red.additionalImages,'');assert.equal(f.view.overrides.options.red['wire-additionalImages'],'');assert.equal(h.control('선택 옵션 추가 이미지 후보 3').props.checked,false);
  await h.click('추가 이미지 공통·자동값 복원');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,3,text(h.render()));assert.deepEqual(f.view.overrides.options.red,{unrelated:'보존'});assert.deepEqual(f.view.overrides.common,before.common);assert.equal(h.control('선택 옵션 추가 이미지 후보 2').props.checked,true);
 }finally{h.close();}
});

test('stage changes retain individual drafts; HTML edits are text, and image changes never replace saved manual HTML',async()=>{
 const f=fixture(),before=plain(f.view.overrides),h=imageUI((url,init)=>f.reply(url,init));try{await h.idle();h.choose('선택 옵션 추가 이미지 후보 3');h.stage('detail');await h.idle();assert.equal(h.render().props['data-workspace-dirty'],true);assert.ok(nodes(h.render()).some(node=>node.props?.className==='option-detail-image-stack'));assert.ok(nodes(h.render()).some(node=>node.type==='details'&&node.props.className==='option-detail-image-candidates'));assert.ok(nodes(h.render()).every(node=>node.props?.className!=='image-edit-workspace'));assert.equal(nodes(h.render()).filter(node=>node.props?.className==='option-detail-image-item').length,1);h.choose('선택 옵션 상세 이미지 후보 1');await h.click('상세 이미지 2 위로 이동');const html='<p>직접 작성</p><script>window.shouldNeverExecute=true</script>';h.html(html);await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,1,text(h.render()));const values=f.view.overrides.options.red;assert.equal(values.additionalImages,f.keys[1]+'\n'+f.keys[2]);assert.equal(values.detailImages,f.keys[0]+'\n'+f.keys[2]);assert.equal(values.detailHtml,html);assert.equal(values['wire-detailHtml'],html);assert.equal(h.control('선택 옵션 상세 HTML').props.value,html);assert.ok(nodes(h.render()).every(node=>!node.props?.dangerouslySetInnerHTML&&!['iframe','script'].includes(node.type)));
  await h.click('상세 이미지 2 선택 제거');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,2);assert.equal(f.view.overrides.options.red.detailHtml,html);assert.equal(f.view.overrides.options.red['wire-detailHtml'],html);
  await h.click('상세 HTML 비우기');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,3);assert.equal(f.view.overrides.options.red.detailHtml,'');await h.click('상세 HTML 공통·자동값 복원');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,4);assert.equal(h.control('선택 옵션 상세 HTML').props.value,before.common['wire-detailHtml']);assert.deepEqual(f.view.overrides.common,before.common);assert.deepEqual(f.view.overrides.options.blue,before.options.blue);
 }finally{h.close();}
});

test('stale callbacks read the newest image draft and duplicate save attempts submit only one PUT',async()=>{
 const f=fixture(),pending=deferred();let held;const h=imageUI((url,init)=>{if(init?.method==='PUT'){held={url,init};return pending.promise;}return f.reply(url,init);});try{await h.idle();h.choose('선택 옵션 추가 이미지 후보 3');const submit=h.button('선택 옵션 이미지 저장').props.onClick;h.choose('선택 옵션 추가 이미지 후보 4');submit();submit();assert.equal(h.calls.filter(call=>call.init?.method==='PUT').length,1);assert.ok(JSON.parse(held.init.body).changes.every(change=>change.value===f.keys.slice(1).join('\n')));pending.resolve(f.reply(held.url,held.init));await h.idle();assert.equal(h.saved,1);assert.equal(h.render().props['data-workspace-dirty'],false);
 }finally{h.close();}
});

test('conflicting saves and reads preserve selections until explicit cancellation',async()=>{
 const f=fixture(),h=imageUI((url,init)=>f.reply(url,init));try{await h.idle();h.choose('선택 옵션 추가 이미지 후보 3');f.reply('',{method:'PUT',body:JSON.stringify({expectedRevision:1,changes:[{optionId:'red',fieldKey:'wire-additionalImages',value:f.keys[3]}]})});await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,0);assert.equal(h.control('선택 옵션 추가 이미지 후보 3').props.checked,true);assert.match(text(h.render()),/동시 이미지 수정/);h.source(f.view.productVersion);await h.idle();const writes=h.calls.filter(call=>call.init?.method==='PUT').length;await h.click('입력 유지·최신 이미지 조회');assert.match(text(h.render()),/다른 저장값/);assert.equal(h.control('선택 옵션 추가 이미지 후보 3').props.checked,true);assert.equal(h.calls.filter(call=>call.init?.method==='PUT').length,writes);await h.click('입력 취소·저장 이미지 다시 조회');assert.equal(h.control('선택 옵션 추가 이미지 후보 4').props.checked,true);assert.equal(h.render().props['data-workspace-dirty'],false);
 }finally{h.close();}
});

test('a committed PUT with a lost ACK is recovered by an explicit read without a parent-version refresh or an automatic retry',async()=>{
 const f=fixture();let lose=true;const h=imageUI((url,init)=>{const response=f.reply(url,init);if(init?.method==='PUT'&&lose){lose=false;throw Error('저장 응답 유실');}return response;});try{await h.idle();h.choose('선택 옵션 추가 이미지 후보 3');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,0);assert.match(text(h.render()),/저장 응답 유실/);assert.equal(f.view.overrides.options.red['wire-additionalImages'],f.keys[1]+'\n'+f.keys[2]);assert.equal(h.render().props['data-workspace-dirty'],true);
  const writes=h.calls.filter(call=>call.init?.method==='PUT').length;await h.click('입력 유지·최신 이미지 조회');assert.equal(h.calls.filter(call=>call.init?.method==='PUT').length,writes);assert.equal(h.saved,0);assert.equal(h.control('선택 옵션 추가 이미지 후보 3').props.checked,true);assert.match(text(h.render()),/입력을 유지하고 최신 이미지를 읽었습니다/);await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,1,text(h.render()));assert.equal(h.render().props['data-workspace-dirty'],false);
 }finally{h.close();}
});

test('reset acknowledgements must match actual common image fallbacks and freshly computed automatic HTML',async()=>{
 const f=fixture();f.reply('',{method:'PUT',body:JSON.stringify({expectedRevision:1,changes:[{optionId:'red',fieldKey:'additionalImages',value:f.keys[3]},{optionId:'red',fieldKey:'wire-additionalImages',value:f.keys[3]}]})});const image=imageUI((url,init)=>{const response=f.reply(url,init);if(init?.method==='PUT'){const body=plain(f.view);body.resolved.rows[0].fields['wire-additionalImages'].value=f.keys[3];return Response.json(body);}return response;},{version:f.view.productVersion});try{await image.idle();await image.click('추가 이미지 공통·자동값 복원');await image.click('선택 옵션 이미지 저장');assert.equal(image.saved,0);assert.equal(image.render().props['data-workspace-dirty'],true);assert.match(text(image.render()),/요청한 값과 다릅니다/);assert.equal(image.control('선택 옵션 추가 이미지 후보 2').props.checked,true);
 }finally{image.close();}
 const g=fixture();delete g.view.overrides.common.detailHtml;delete g.view.overrides.common['wire-detailHtml'];g.reply('',{method:'PUT',body:JSON.stringify({expectedRevision:1,changes:[{optionId:'red',fieldKey:'detailHtml',value:'<p>개별 HTML</p>'},{optionId:'red',fieldKey:'wire-detailHtml',value:'<p>개별 HTML</p>'}]})});let corrupt=true;const html=imageUI((url,init)=>{const response=g.reply(url,init);if(init?.method==='PUT'&&corrupt){const body=plain(g.view);for(const id of ['detailHtml','wire-detailHtml'])body.resolved.rows[0].fields[id].value='<p>잘못된 자동 HTML 응답</p>';return Response.json(body);}return response;},{version:g.view.productVersion,stage:'detail'});try{await html.idle();await html.click('상세 HTML 공통·자동값 복원');await html.click('선택 옵션 이미지 저장');assert.equal(html.saved,0);assert.equal(html.render().props['data-workspace-dirty'],true);assert.match(text(html.render()),/최종값이 최신 저장본과 다릅니다/);assert.equal(html.control('선택 옵션 상세 HTML').props.value,'<p>자동 상세</p>');const writes=html.calls.filter(call=>call.init?.method==='PUT').length;await html.click('입력 유지·최신 이미지 조회');assert.equal(html.calls.filter(call=>call.init?.method==='PUT').length,writes);corrupt=false;await html.click('선택 옵션 이미지 저장');assert.equal(html.saved,1,text(html.render()));assert.equal(html.control('선택 옵션 상세 HTML').props.value,'<p>자동 상세</p>');
 }finally{html.close();}
});

test('source commit changes and option switches abort stale replies and prevent captured callbacks from editing another SKU',async()=>{
 for(const mode of ['version','refresh']){const f=fixture(),pending=deferred();let held;const h=imageUI((url,init)=>{if(init?.method==='PUT'){held={url,init};return pending.promise;}return f.reply(url,init);});try{await h.idle();h.choose('선택 옵션 추가 이미지 후보 3');const oldSubmit=h.button('선택 옵션 이미지 저장').props.onClick;oldSubmit();h.source(mode==='version'?advance(initialVersion):initialVersion,mode==='refresh'?'1':'0',false);assert.equal(held.init.signal.aborted,true);pending.resolve(f.reply(held.url,held.init));await new Promise(resolve=>setImmediate(resolve));assert.equal(h.saved,0);await h.idle();assert.equal(h.control('선택 옵션 추가 이미지 후보 3').props.checked,true);const writes=h.calls.filter(call=>call.init?.method==='PUT').length;oldSubmit();await h.idle();assert.equal(h.calls.filter(call=>call.init?.method==='PUT').length,writes);
 }finally{h.close();}}
 const f=fixture(),h=imageUI((url,init)=>f.reply(url,init));try{await h.idle();const oldChoice=h.control('선택 옵션 추가 이미지 후보 3').props.onChange,oldSave=h.button('선택 옵션 이미지 저장').props.onClick;h.select('blue');await h.idle();oldChoice();oldSave();await h.idle();assert.equal(h.control('선택 옵션 추가 이미지 후보 4').props.checked,true);assert.equal(h.render().props['data-workspace-dirty'],false);assert.equal(h.calls.some(call=>call.init?.method==='PUT'),false);
 }finally{h.close();}
 const pending=deferred(),closing=imageUI(()=>pending.promise);await Promise.resolve();const request=closing.calls[0];closing.close();assert.equal(request.init.signal.aborted,true);pending.resolve(Response.json(f.view));await new Promise(resolve=>setImmediate(resolve));assert.equal(closing.lateWrites,0);
});

test('ambiguous bindings, missing image references and malformed save acknowledgements remain conservative and editable',async()=>{
 const bad=fixture();bad.view.resolved.schema.fields.push({...bad.view.resolved.schema.fields.at(-1),id:'duplicate-html'});const invalid=imageUI(()=>Response.json(bad.view));try{await invalid.idle();assert.equal(invalid.button('선택 옵션 이미지 저장').props.disabled,true);assert.equal(invalid.control('선택 옵션 추가 이미지 후보 1'),undefined);assert.equal(invalid.calls.some(call=>call.init?.method==='PUT'),false);}finally{invalid.close();}
 const missing=fixture();missing.view.resolved.rows[0].fields['wire-additionalImages'].value='owner/missing.png';const repair=imageUI((url,init)=>missing.reply(url,init));try{await repair.idle();assert.match(text(repair.render()),/현재 상품에 없는 이미지 참조/);await repair.click('누락 이미지 참조 제거');await repair.click('선택 옵션 이미지 저장');assert.equal(repair.saved,1);assert.equal(missing.view.overrides.options.red.additionalImages,'');}finally{repair.close();}
 for(const corrupt of [body=>body.revision++,body=>body.contentRevision++,body=>body.overrides.common.detailHtml='응답에서 바뀐 공통 HTML',body=>body.overrides.options.blue.detailImages='']){const f=fixture(),h=imageUI((url,init)=>{const response=f.reply(url,init);if(init?.method==='PUT'){const body=plain(f.view);corrupt(body);return Response.json(body);}return response;});try{await h.idle();h.choose('선택 옵션 추가 이미지 후보 3');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,0);assert.equal(h.control('선택 옵션 추가 이미지 후보 3').props.checked,true);assert.equal(h.render().props['data-workspace-dirty'],true);}finally{h.close();}}
});

// Actual UI callbacks/native handlers/SQLite plus generated XLSX and ZIP. Auth,
// supplier source/media, public signing origin and workbook are private fixtures;
// no real Couplus/Supplier Hub product is changed or transmitted.
for(const company of [{companyCode:'A01464742',companyName:'와이홉'},{companyCode:'A01526306',companyName:'유앤채'}])test(`selected image order, manual HTML and clear/reset reach XLSX and exact ZIP references (${company.companyCode})`,async()=>{
 const api=mobileIntakeHarness(company);let h;try{
  api.bindings.YOOFAM_DETAIL_IMAGE_SECRET='ab'.repeat(32);api.bindings.YOOFAM_DETAIL_IMAGE_ORIGIN='https://private-image-fixture.example';const put=api.bindings.FILES.put;api.bindings.FILES.put=async(key,bytes,options)=>{const result=await put(key,bytes,options);return result===null?null:api.bindings.FILES.head(key);};
  const live={format:'supplier-hub-schema-v1',categoryId:'80719',categoryPath:api.context.category.categoryPath,company:{code:company.companyCode,name:company.companyName},observedAt:Date.now(),inputBindings:'couplus-paths-v1',metadata:{kanCategoryId:80719,noticeNumber:1,scopeType:'Retail_Categorized_Single',version:1},schemaString:JSON.stringify({type:'object',properties:{startPage:{type:'object',properties:{productName:{type:'string',title:'상품명'}}},productPage:{type:'object',properties:{}},imagePage:{type:'object',properties:{images:{type:'object',properties:{additionalImage:{type:'string',title:'추가 이미지'}}},details:{type:'object',properties:{detailedImage:{type:'string',title:'상세 이미지'},htmlProductDetailContent:{type:'string',title:'HTML 상세 내용'}}}}},legalPage:{type:'object',properties:{}}}})};
  const schema=api.load('app/quotation-schema.ts').getQuotationSchema('80719',live.categoryPath,live),fields=schema.fields.map(field=>field.id),workbook=quotationWorkbook(fields),sha256=Buffer.from(await crypto.subtle.digest('SHA-256',workbook)).toString('hex'),storageKey=api.load('db/category-templates.ts').templateKey('owner',sha256,'xlsx');api.objects.set(storageKey,workbook);
  const profile=await api.load('db/category-profiles.ts').createCategoryProfile('owner',{name:'옵션 추가·상세 이미지 연결 시험',categoryId:'80719',categoryPath:live.categoryPath,hubSchema:live,template:{name:'synthetic-option-images.xlsx',format:'xlsx',sha256,storageKey,sheetName:'견적서',headerRow:1,headers:fields},mappings:fields.map((field,column)=>({field,column,required:false}))},'cat');api.context.category=profile;api.sqlite.prepare('UPDATE collection_context SET payload=? WHERE job_id=?').run(JSON.stringify(api.context),'job');await api.intake();
  const product=api.sqlite.prepare('SELECT * FROM products').get(),base='/api/products/'+product.id,qurl=base+'/quotation-fields',keys=JSON.parse(product.image_keys);assert.ok(keys.length>=5);let current=await json(await api.route(qurl));
  current=await json(await api.route(qurl,{method:'PUT',body:{expectedRevision:current.revision,expectedInputFingerprint:current.inputFingerprint,changes:[{optionId:null,fieldKey:'additionalImages',value:keys[0]},{optionId:null,fieldKey:'detailImages',value:keys[1]+'\n'+keys[2]}]}}));
  const target=current.resolved.rows.find(row=>row.optionId),other=current.resolved.rows.filter(row=>row.optionId)[1],common=plain(current.overrides.common),otherFields=plain(other.fields),contentBefore=api.sqlite.prepare('SELECT payload FROM product_content').get().payload,optionsBefore=api.sqlite.prepare('SELECT payload FROM product_options').get().payload,policyBefore=api.sqlite.prepare('SELECT payload FROM product_price_policy').get().payload;
  h=imageUI((url,init)=>api.route(url,{method:init?.method??'GET',...(init?.body?{body:JSON.parse(init.body)}:{})}),{productId:product.id,optionId:target.optionId,version:current.productVersion,profileId:profile.id});await h.idle();assert.equal(h.calls.some(call=>call.init?.method==='PUT'),false);
  h.choose('선택 옵션 추가 이미지 후보 4');await h.click('추가 이미지 2 위로 이동');await h.click('추가 이미지 2 선택 제거');h.stage('detail');await h.click('상세 이미지 선택 비우기');h.choose('선택 옵션 상세 이미지 후보 5');h.choose('선택 옵션 상세 이미지 후보 4');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,1,text(h.render()));current=await json(await api.route(qurl));let selected=current.resolved.rows.find(row=>row.optionId===target.optionId);assert.equal(selected.fields.additionalImages.value,keys[3]);assert.equal(selected.fields.detailImages.value,keys[4]+'\n'+keys[3]);assert.deepEqual(plain(current.overrides.common),common);assert.deepEqual(plain(current.resolved.rows.find(row=>row.optionId===other.optionId).fields),otherFields);
  const detail=await api.load('app/quotation-public-detail.ts').resolvePublicDetail(current.resolved,JSON.parse(contentBefore),'owner',keys,api.load('app/quotation-public-detail.ts').publicDetailConfig(api.bindings)),urls=detail.images;const url4=urls.find(image=>image.key===keys[4]).url,url3=urls.find(image=>image.key===keys[3]).url;assert.ok(selected.fields.detailHtml.value.indexOf(url4)<selected.fields.detailHtml.value.indexOf(url3));
  const exportZip=async()=>{const preview=await json(await api.route(base+'/quotation',{method:'POST',body:{action:'preview',profileId:profile.id}}));const result=await api.route(base+'/quotation',{method:'POST',body:{action:'export',profileId:profile.id,fingerprint:preview.fingerprint}});assert.equal(result.status,200,await result.clone().text());const reader=api.load('app/xlsx-template.ts'),archive=await reader.readXlsxArchive(await result.arrayBuffer()),document=JSON.parse(new TextDecoder().decode(archive.get('quotation-fields.json'))),plan=JSON.parse(new TextDecoder().decode(archive.get('supplier-hub-upload-plan.json'))),sheet=reader.inspectXlsxArchive(await reader.readXlsxArchive(archive.get(plan.quotation.file.filename)));return{preview,reader,archive,document,plan,sheet};};
  let exported=await exportZip(),rowIndex=exported.document.rows.findIndex(row=>row.optionId===target.optionId),cells=exported.reader.xlsxHeaders(exported.sheet,'견적서',rowIndex+2);assert.equal(cells[fields.indexOf('additionalImages')],exported.document.uploadFilenames[keys[3]]);assert.equal(cells[fields.indexOf('detailImages')],[keys[4],keys[3]].map(key=>exported.document.uploadFilenames[key]).join('\n'));assert.ok(cells[fields.indexOf('detailHtml')].indexOf(url4)<cells[fields.indexOf('detailHtml')].indexOf(url3));
  for(const key of [keys[4],keys[3]]){const image=exported.plan.productImages.find(image=>image.key===key);assert.ok(image.references.some(ref=>ref.optionId===target.optionId&&ref.fieldId==='detailImages'));assert.deepEqual(Buffer.from(exported.archive.get(image.archivePath)),Buffer.from(api.objects.get(key)));}
  const manual='<p>선택 옵션에 직접 작성한 상세 HTML</p>';h.html(manual);await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,2);await h.click('상세 이미지 2 위로 이동');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,3);current=await json(await api.route(qurl));selected=current.resolved.rows.find(row=>row.optionId===target.optionId);assert.equal(selected.fields.detailHtml.value,manual);assert.equal(selected.fields.detailHtml.source,'manual-option');exported=await exportZip();cells=exported.reader.xlsxHeaders(exported.sheet,'견적서',rowIndex+2);assert.equal(cells[fields.indexOf('detailHtml')],manual);
  await h.click('상세 HTML 비우기');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,4);current=await json(await api.route(qurl));assert.equal(current.resolved.rows.find(row=>row.optionId===target.optionId).fields.detailHtml.value,'');await h.click('상세 HTML 공통·자동값 복원');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,5);
  await h.click('상세 이미지 선택 비우기');h.stage('additional');await h.click('추가 이미지 선택 비우기');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,6);current=await json(await api.route(qurl));selected=current.resolved.rows.find(row=>row.optionId===target.optionId);assert.equal(selected.fields.additionalImages.value,'');assert.equal(selected.fields.detailImages.value,'');assert.ok(!selected.fields.detailHtml.value.includes('<img '));exported=await exportZip();cells=exported.reader.xlsxHeaders(exported.sheet,'견적서',rowIndex+2);assert.equal(cells[fields.indexOf('additionalImages')],'');assert.equal(cells[fields.indexOf('detailImages')],'');assert.ok(exported.plan.productImages.every(image=>!image.references.some(ref=>ref.optionId===target.optionId&&['additionalImages','detailImages'].includes(ref.fieldId))));
  await h.click('추가 이미지 공통·자동값 복원');h.stage('detail');await h.click('상세 이미지 공통·자동값 복원');await h.click('선택 옵션 이미지 저장');assert.equal(h.saved,7);current=await json(await api.route(qurl));selected=current.resolved.rows.find(row=>row.optionId===target.optionId);assert.equal(selected.fields.additionalImages.value,keys[0]);assert.equal(selected.fields.detailImages.value,keys[1]+'\n'+keys[2]);assert.deepEqual(plain(current.overrides.common),common);assert.deepEqual(plain(current.resolved.rows.find(row=>row.optionId===other.optionId).fields),otherFields);
  assert.equal(api.sqlite.prepare('SELECT payload FROM product_content').get().payload,contentBefore);assert.equal(api.sqlite.prepare('SELECT payload FROM product_options').get().payload,optionsBefore);assert.equal(api.sqlite.prepare('SELECT payload FROM product_price_policy').get().payload,policyBefore);assert.equal(api.sqlite.prepare('SELECT supplier_hub_status FROM products').get().supplier_hub_status,'미전송');assert.ok(!api.network.some(host=>/supplier\.coupang|couplus/.test(host)));
 }finally{h?.close();api.close();}
});
