import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import ts from 'typescript';
import {createRequire} from 'node:module';
const native=createRequire(import.meta.url),plain=value=>JSON.parse(JSON.stringify(value));
const nodes=value=>Array.isArray(value)?value.flatMap(nodes):value&&typeof value==='object'?[value,...nodes(value.props?.children)]:[];
const text=value=>Array.isArray(value)?value.map(text).join(''):value&&typeof value==='object'?text(value.props?.children):value==null?'':String(value);
const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return{promise,resolve};};
const initialVersion='2026-10-07T00:00:00.000Z',advance=value=>new Date(Date.parse(value)+1).toISOString();
const definitions=[['productName','제품명'],['manufacturer','제조원'],['importer','수입 및 판매원'],['countryOfOrigin','제조국'],['netContents','내용량'],['material','원료명 및 성분명(재질)'],['productType','상품 유형'],['precautions','사용 시 주의사항'],['usageStandard','사용 기준']];

function fixture(){
 const overrides={common:{material:'공통 재질',netContents:''},options:{red:{productName:'검정 수정 제품명',precautions:'검토한 개별 주의사항'},blue:{productName:'다른 옵션 제품명',material:'다른 옵션 재질',usageStandard:''}}};
 const automatic=optionId=>Object.fromEntries(definitions.map(([key])=>[key,{productName:optionId===null?'공통 원천 상품명':optionId==='red'?'검정 원천 상품명':'파랑 원천 상품명',manufacturer:'원천 제조사',importer:'검토 수입사',countryOfOrigin:'중국',precautions:'용도 외 사용금지'}[key]??'']));
 const rows=()=>[null,'red','blue'].map(optionId=>{const source=automatic(optionId),values={...source},sources=Object.fromEntries(definitions.map(([key])=>[key,source[key]?'content':'empty']));for(const[key]of definitions){const own=optionId===null?undefined:overrides.options[optionId];if(own&&Object.hasOwn(own,key)){values[key]=own[key];sources[key]='manual-option';}else if(Object.hasOwn(overrides.common,key)){values[key]=overrides.common[key];sources[key]='manual-common';}}return{optionId,optionLabel:optionId??'',included:optionId!==null,values,automatic:source,sources};});
 const view={productId:'p',revision:1,inputFingerprint:'a'.repeat(64),productVersion:initialVersion,contentRevision:2,optionRevision:3,quotationRevision:4,quotationInputFingerprint:'b'.repeat(64),categoryContext:{source:'profile',profileId:'cat',categoryId:'80719',categoryPath:['주방']},imageKeys:['owner/existing.png'],overrides,rows:rows(),updatedAt:initialVersion};
 return{view,reply(url,init){if(init?.method==='PUT'){const body=JSON.parse(init.body);if(body.expectedRevision!==view.revision||body.expectedInputFingerprint!==view.inputFingerprint)return Response.json({error:'표시사항 동시 수정'},{status:409});for(const change of body.changes){const values=change.optionId===null?overrides.common:(overrides.options[change.optionId]??={});if(change.value===null)delete values[change.fieldKey];else values[change.fieldKey]=change.value;if(change.optionId!==null&&!Object.keys(values).length)delete overrides.options[change.optionId];}view.revision++;view.productVersion=advance(view.productVersion);view.updatedAt=view.productVersion;view.inputFingerprint='abcdef'[view.revision%6].repeat(64);view.quotationInputFingerprint='bcdefa'[view.revision%6].repeat(64);view.rows=rows();}return Response.json(view);},source(){view.productVersion=advance(view.productVersion);view.inputFingerprint='c'.repeat(64);view.quotationInputFingerprint='d'.repeat(64);return view.productVersion;}};
}

function editor(fetcher,{productId='p',optionId='red',version=initialVersion,profileId='cat',refreshToken='0',renderer,attach}={}){
 const slots=[],effects=[],layouts=[],cache=new Map(),calls=[],plans=[],attachments=[],urls=[],revoked=[];let cursor=0,saved=0,stateEpoch=0,closed=false,lateWrites=0,lastVersion=version;
 const effect=(queue,fn,deps)=>{const i=cursor++;if(!slots[i]||JSON.stringify(slots[i].deps)!==JSON.stringify(deps)){const old=slots[i],next={deps,cleanup:old?.cleanup};slots[i]=next;queue.push(()=>{old?.cleanup?.();next.cleanup=fn();});}};
 const react={useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],value=>{if(closed){lateWrites++;return;}stateEpoch++;slots[i]=typeof value==='function'?value(slots[i]):value;}];},useRef(initial){const i=cursor++;return slots[i]??(slots[i]={current:initial});},useEffect(fn,deps){effect(effects,fn,deps);},useLayoutEffect(fn,deps){effect(layouts,fn,deps);}};
 const localURL={createObjectURL(blob){assert.equal(blob.type,'image/png');const url='blob:product-label-'+(urls.length+1);urls.push(url);return url;},revokeObjectURL(url){revoked.push(url);}};
 const request=async(url,init)=>{calls.push({url,init});const response=await fetcher(url,init);if(response.ok){const body=await response.clone().json();if(body.productVersion)lastVersion=body.productVersion;}return response;};
 function load(file){if(cache.has(file))return cache.get(file);const exports={};cache.set(file,exports);vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,Error,AbortController,structuredClone,TextEncoder,URL:localURL,fetch:request,require(name){if(name==='react')return react;if(name==='react/jsx-runtime')return{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};if(name==='@/app/document-image-render')return{renderDocument:async plan=>{plans.push(plain(plan));return renderer?renderer(plan):{blob:new Blob(['private fixture PNG'],{type:'image/png'}),width:800,height:900};}};if(name==='@/app/product-label-attachment')return{attachProductLabel:async(input,scoped)=>{attachments.push(input);if(!attach)throw Error('private attachment fixture unavailable');return attach(input,scoped);}};if(name.startsWith('./')||name.startsWith('../'))return load(path.posix.join(path.posix.dirname(file),name)+'.ts');return name.startsWith('@/')?load(name.slice(2)+'.ts'):native(name);}});return exports;}
 const Component=load('app/components/product-label-editor.tsx').ProductLabelEditor;
 const render=(flush=true)=>{cursor=0;const tree=Component({productId,optionId,version,profileId,refreshToken,onSaved(){saved++;stateEpoch++;version=lastVersion;}});layouts.splice(0).forEach(fn=>fn());if(flush)effects.splice(0).forEach(fn=>fn());return tree;};
 const idle=async()=>{let quiet=0;const deadline=Date.now()+10000;for(;;){const epoch=stateEpoch,count=calls.length,previous=version;render();await new Promise(resolve=>setImmediate(resolve));render();await Promise.resolve();const tree=render();if(!tree.props['data-workspace-saving']&&epoch===stateEpoch&&count===calls.length&&previous===version&&!effects.length&&!layouts.length)quiet++;else quiet=0;if(quiet===2)return;assert.ok(Date.now()<deadline,'product label editor timed out');await new Promise(resolve=>setTimeout(resolve,1));}};
 const input=label=>nodes(render()).find(node=>node.type==='textarea'&&node.props['aria-label']===label),button=label=>nodes(render()).find(node=>node.type==='button'&&text(node)===label);
 render();return{render,load,calls,plans,attachments,urls,revoked,input,button,idle,get saved(){return saved;},get lateWrites(){return lateWrites;},source(nextVersion,nextRefresh=refreshToken,flush=true){version=nextVersion;refreshToken=nextRefresh;render(flush);},select(id){optionId=id;render();},close(){closed=true;slots.forEach(slot=>slot?.cleanup?.());},edit(label,value){const target=input(label);assert.ok(target&&!target.props.disabled,'available product label field '+label);target.props.onChange({target:{value}});},async click(label){const target=button(label);assert.ok(target&&!target.props.disabled,'available product label button '+label+' '+text(render()));target.props.onClick();await idle();}};
}

test('stage six opens exactly the nine product-label captions without writes or category legal notices',async()=>{
 const f=fixture(),before=plain(f.view),h=editor((url,init)=>f.reply(url,init));try{await h.idle();assert.equal(h.render().props['data-quotation-source-step'],'표시사항');assert.equal(h.render().props['data-source-step'],'표시사항');assert.deepEqual(nodes(h.render()).filter(node=>node.type==='textarea').map(node=>node.props['aria-label']),definitions.map(([,label])=>'선택 옵션 '+label));assert.equal(h.input('선택 옵션 내용량').props.value,'');assert.equal(h.input('선택 옵션 상품 유형').props.value,'');assert.equal(h.input('선택 옵션 사용 기준').props.value,'');assert.equal(h.calls.some(call=>call.init?.method==='PUT'),false);assert.deepEqual(f.view,before);
 }finally{h.close();}
});

test('individual saves, manual blanks and restore preserve common and other-option labels and their source revisions',async()=>{
 const f=fixture(),before=plain(f.view),h=editor((url,init)=>f.reply(url,init));try{await h.idle();h.edit('선택 옵션 제품명','선택한 검정 제품');h.edit('선택 옵션 원료명 및 성분명(재질)','');await h.click('정보 저장하기');assert.equal(h.saved,1,text(h.render()));assert.deepEqual(JSON.parse(h.calls.find(call=>call.init?.method==='PUT').init.body).changes,[{optionId:'red',fieldKey:'productName',value:'선택한 검정 제품'},{optionId:'red',fieldKey:'material',value:''}]);assert.deepEqual(f.view.overrides.common,before.overrides.common);assert.deepEqual(f.view.overrides.options.blue,before.overrides.options.blue);assert.equal(f.view.rows.find(row=>row.optionId==='red').values.material,'');assert.equal(f.view.contentRevision,before.contentRevision);assert.equal(f.view.optionRevision,before.optionRevision);assert.equal(f.view.quotationRevision,before.quotationRevision);assert.deepEqual(f.view.imageKeys,before.imageKeys);
  assert.match(text(h.render()),/수정한 내용을 견적서 이미지에 반영하려면 다시 생성한 뒤 PNG를 견적에 연결하세요/);assert.equal(h.attachments.length,0);await h.click('제품명 공통·자동값 복원');await h.click('원료명 및 성분명(재질) 공통·자동값 복원');await h.click('정보 저장하기');assert.equal(h.saved,2);assert.equal(h.input('선택 옵션 제품명').props.value,'검정 원천 상품명');assert.equal(h.input('선택 옵션 원료명 및 성분명(재질)').props.value,'공통 재질');assert.deepEqual(f.view.overrides.options.red,{precautions:'검토한 개별 주의사항'});assert.deepEqual(f.view.overrides.options.blue,before.overrides.options.blue);
 }finally{h.close();}
});

test('common editing uses dedicated null-option changes and keeps independent SKU overrides intact',async()=>{
 const f=fixture(),before=plain(f.view.overrides.options),h=editor((url,init)=>f.reply(url,init),{optionId:null});try{await h.idle();assert.equal(h.render().props['aria-label'],'상품 공통 제품 표시사항');h.edit('상품 공통 제조원','공통 검토 제조원');h.edit('상품 공통 원료명 및 성분명(재질)','');await h.click('정보 저장하기');assert.equal(h.saved,1);assert.ok(JSON.parse(h.calls.find(call=>call.init?.method==='PUT').init.body).changes.every(change=>change.optionId===null));assert.deepEqual(f.view.overrides.options,before);assert.equal(f.view.rows.find(row=>row.optionId==='blue').values.material,'다른 옵션 재질');assert.equal(f.view.rows.find(row=>row.optionId==='red').values.material,'');await h.click('원료명 및 성분명(재질) 자동값 복원');await h.click('정보 저장하기');assert.equal(h.saved,2);assert.equal(Object.hasOwn(f.view.overrides.common,'material'),false);assert.deepEqual(f.view.overrides.options,before);
  await h.click('한글 표시사항 생성 시작');assert.equal(h.plans.length,1);assert.equal(h.plans[0].format,'product-label');assert.deepEqual(h.plans[0].rows.map(row=>row[0]),definitions.map(([,label])=>label));assert.equal(h.calls.some(call=>call.url==='/api/files'),false);
 }finally{h.close();}
});

test('synchronous edits and duplicate submission callbacks send the newest draft only once',async()=>{
 const f=fixture(),pending=deferred();let held;const h=editor((url,init)=>{if(init?.method==='PUT'){held={url,init};return pending.promise;}return f.reply(url,init);});try{await h.idle();h.edit('선택 옵션 제품명','이전 입력');const submit=h.button('정보 저장하기').props.onClick;h.edit('선택 옵션 제품명','최신 입력');submit();submit();assert.equal(h.calls.filter(call=>call.init?.method==='PUT').length,1);assert.equal(JSON.parse(held.init.body).changes[0].value,'최신 입력');pending.resolve(f.reply(held.url,held.init));await h.idle();assert.equal(h.saved,1);assert.equal(h.input('선택 옵션 제품명').props.value,'최신 입력');
 }finally{h.close();}
});

test('lost-ACK recovery is read only and confirms the exact committed labels without retrying a PUT',async()=>{
 const f=fixture();let lose=true;const h=editor((url,init)=>{const response=f.reply(url,init);if(init?.method==='PUT'&&lose){lose=false;throw Error('표시사항 응답 유실');}return response;});try{await h.idle();h.edit('선택 옵션 내용량','검토한 1개');await h.click('정보 저장하기');assert.equal(h.saved,0);assert.equal(h.render().props['data-workspace-dirty'],true);assert.equal(f.view.overrides.options.red.netContents,'검토한 1개');const writes=h.calls.filter(call=>call.init?.method==='PUT').length;await h.click('입력 유지·최신 표시사항 조회');assert.equal(h.calls.filter(call=>call.init?.method==='PUT').length,writes);assert.equal(h.saved,1);assert.equal(h.render().props['data-workspace-dirty'],false);assert.equal(h.input('선택 옵션 내용량').props.value,'검토한 1개');
 }finally{h.close();}
});

test('conflicts and failed reads retain drafts; cancellation is an explicit latest-source read',async()=>{
 const f=fixture();let offline=false;const h=editor((url,init)=>offline?Response.json({error:'표시사항 조회 실패'},{status:503}):f.reply(url,init));try{await h.idle();h.edit('선택 옵션 제품명','보관할 입력');f.reply('',{method:'PUT',body:JSON.stringify({expectedRevision:1,expectedInputFingerprint:f.view.inputFingerprint,changes:[{optionId:'red',fieldKey:'productName',value:'다른 사용자가 저장한 값'}]})});await h.click('정보 저장하기');assert.equal(h.saved,0);assert.equal(h.input('선택 옵션 제품명').props.value,'보관할 입력');await h.click('입력 유지·최신 표시사항 조회');assert.match(text(h.render()),/다른 저장값/);assert.equal(h.input('선택 옵션 제품명').props.value,'보관할 입력');offline=true;await h.click('입력 유지·최신 표시사항 조회');assert.match(text(h.render()),/조회 실패/);assert.equal(h.input('선택 옵션 제품명').props.value,'보관할 입력');offline=false;await h.click('입력 취소·저장 표시사항 다시 조회');assert.equal(h.input('선택 옵션 제품명').props.value,'다른 사용자가 저장한 값');assert.equal(h.render().props['data-workspace-dirty'],false);
 }finally{h.close();}
});

test('preview uses only saved nine-row values, literal blanks and stable PNG cache; local editing invalidates it',async()=>{
 const f=fixture(),h=editor((url,init)=>f.reply(url,init));try{await h.idle();await h.click('한글 표시사항 생성 시작');assert.equal(h.plans.length,1);const plan=h.plans[0];assert.equal(plan.format,'product-label');assert.equal(plan.width,800);assert.equal(plan.rows.length,9);assert.equal(plan.rows.find(row=>row[0]==='내용량')[1],'');assert.equal(plan.rows.find(row=>row[0]==='사용 기준')[1],'');const download=nodes(h.render()).find(node=>node.type==='a');assert.equal(download.props.download,'yoofam-product-label.png');assert.equal(download.props.href,h.urls[0]);await h.click('저장한 값으로 다시 생성');assert.equal(h.plans.length,1,'an unchanged saved plan reuses its rendered bytes');assert.ok(h.revoked.includes(h.urls[0]));h.edit('선택 옵션 제조국','');assert.equal(nodes(h.render()).some(node=>node.type==='a'),false);assert.equal(h.button('한글 표시사항 생성 시작').props.disabled,true);assert.equal(h.calls.some(call=>call.init?.method==='PUT'||call.url==='/api/files'),false);
 }finally{h.close();}
});

test('source or selected-option changes abort late saves and renders before passive cleanup can publish them',async()=>{
 for(const mode of ['version','refresh']){const f=fixture(),pending=deferred();let held;const h=editor((url,init)=>{if(init?.method==='PUT'){held={url,init};return pending.promise;}return f.reply(url,init);});try{await h.idle();h.edit('선택 옵션 제품명','남겨둘 초안');const oldEdit=h.input('선택 옵션 제품명').props.onChange,oldSubmit=h.button('정보 저장하기').props.onClick;oldSubmit();h.source(mode==='version'?advance(initialVersion):initialVersion,mode==='refresh'?'1':'0',false);assert.equal(held.init.signal.aborted,true);pending.resolve(f.reply(held.url,held.init));await h.idle();assert.equal(h.saved,0);oldEdit({target:{value:'늦은 입력'}});oldSubmit();await h.idle();assert.equal(h.input('선택 옵션 제품명').props.value,'남겨둘 초안');assert.equal(h.calls.filter(call=>call.init?.method==='PUT').length,1);
 }finally{h.close();}}
 const f=fixture(),rendered=deferred(),h=editor((url,init)=>f.reply(url,init),{renderer:()=>rendered.promise});try{await h.idle();h.button('한글 표시사항 생성 시작').props.onClick();const deadline=Date.now()+10000;while(!h.plans.length){assert.ok(Date.now()<deadline);await new Promise(resolve=>setImmediate(resolve));h.render();}h.source(f.source());rendered.resolve({blob:new Blob(['private'],{type:'image/png'}),width:800,height:900});await h.idle();assert.equal(h.urls.length,0);assert.equal(nodes(h.render()).some(node=>node.type==='a'),false);const oldEdit=h.input('선택 옵션 제품명').props.onChange;h.select('blue');await h.idle();oldEdit({target:{value:'이전 옵션 입력'}});assert.equal(h.input('선택 옵션 제품명').props.value,'다른 옵션 제품명');assert.equal(h.calls.some(call=>call.init?.method==='PUT'),false);
 }finally{h.close();}
 const held=deferred(),closing=editor(()=>held.promise);await Promise.resolve();const request=closing.calls[0];closing.close();assert.equal(request.init.signal.aborted,true);held.resolve(Response.json(f.view));await new Promise(resolve=>setImmediate(resolve));assert.equal(closing.lateWrites,0);
});

test('attachment retry retains the reviewed recipe key and uses the final product clock without rerendering its PNG',async()=>{
 const f=fixture();let fail=true;const key='owner/generated-product-label.png';const h=editor((url,init)=>f.reply(url,init),{attach:async(input,request)=>{input.onUploaded(key);if(fail){fail=false;throw Error('private fixture connection failure');}assert.equal(input.uploadedKey,key);f.view.imageKeys.push(key);f.view.quotationRevision++;f.source();const view=await(await request(input.endpoint,{cache:'no-store'})).json();return{view,quotation:{},key};}});try{await h.idle();await h.click('한글 표시사항 생성 시작');await h.click('PNG 업로드·견적에 연결');assert.equal(h.saved,0);assert.match(text(h.render()),/업로드한 파일은 보존/);assert.equal(h.plans.length,1);await h.click('PNG 업로드·견적에 연결');assert.equal(h.saved,1);assert.equal(h.attachments.length,2);assert.equal(h.attachments[1].uploadedKey,key);assert.equal(h.plans.length,1);assert.equal(nodes(h.render()).some(node=>node.type==='a'),false);assert.match(text(h.render()),/선택 옵션 표시사항 PNG를 견적서에 연결/);
  h.source(f.source());await h.idle();assert.equal(h.saved,1);assert.doesNotMatch(text(h.render()),/선택 옵션 표시사항 PNG를 견적서에 연결/,'another source clock must not retain the old attachment confirmation');
 }finally{h.close();}
});

test('wrong source identity, malformed save ACKs and overlong values cannot replace local label edits',async()=>{
 const stale=fixture();stale.source();const invalid=editor((url,init)=>stale.reply(url,init));try{await invalid.idle();assert.equal(invalid.input('선택 옵션 제품명'),undefined);assert.match(text(invalid.render()),/상품 저장 상태가 변경/);assert.equal(invalid.calls.some(call=>call.init?.method==='PUT'),false);}finally{invalid.close();}
 const f=fixture(),h=editor((url,init)=>{const response=f.reply(url,init);if(init?.method==='PUT'){const wrong=plain(f.view);wrong.overrides.options.blue.material='다른 옵션을 응답에서 변조';return Response.json(wrong);}return response;});try{await h.idle();h.edit('선택 옵션 제품명','남겨둘 직접 입력');await h.click('정보 저장하기');assert.equal(h.saved,0);assert.equal(h.input('선택 옵션 제품명').props.value,'남겨둘 직접 입력');assert.equal(h.render().props['data-workspace-dirty'],true);h.edit('선택 옵션 제품명','가'.repeat(2001));assert.equal(h.button('정보 저장하기').props.disabled,true);assert.equal(h.input('선택 옵션 제품명').props.value,'가'.repeat(2001));
 }finally{h.close();}
});
