'use client';
import {useEffect,useState} from 'react';
import type {WorkspaceMember} from '@/app/workspace-members';
export default function AccountPage(){
 const [self,setSelf]=useState<WorkspaceMember|null>(null),[members,setMembers]=useState<WorkspaceMember[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){const response=await fetch('/api/membership',{cache:'no-store'});const data=await response.json() as {error?:string;member:WorkspaceMember;members?:WorkspaceMember[]};if(!response.ok)throw Error(data.error);setSelf(data.member);setMembers(data.members??[]);}
 useEffect(()=>{refresh().catch(error=>setMessage(error.message));},[]);
 async function act(action:string,memberId?:string,company?:{companyCode:string;companyName:string}){setBusy(true);setMessage('');try{const response=await fetch('/api/membership',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,memberId,...company})});const data=await response.json() as {error?:string;member:WorkspaceMember;members?:WorkspaceMember[]};if(!response.ok)throw Error(data.error);if(action==='logout')window.location.assign('/login');else await refresh();}catch(error){setMessage(error instanceof Error?error.message:'처리 실패');}finally{setBusy(false);}}
 const labels={pending:'승인 대기',approved:'승인',rejected:'거절',suspended:'이용 정지'};
 return <main style={{maxWidth:1000,margin:'50px auto',padding:24}}><a href="/">← 상품등록</a><h1>YOOFAM PLUS 계정 관리</h1>{self&&<><p>{self.email} · {self.role==='admin'?'관리자':'회원'}</p><p>{self.companyName||'회사정보 미설정'} {self.companyCode}</p><button disabled={busy} onClick={()=>act('logout')}>로그아웃</button></>}<p role="status">{message}</p>{self?.role==='admin'&&<><h2>관리자 회사정보</h2><form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void act('company',undefined,{companyCode:String(data.get('companyCode')),companyName:String(data.get('companyName'))});}}><label>회사코드 <input name="companyCode" defaultValue={self.companyCode} required maxLength={200}/></label><label>회사명 <input name="companyName" defaultValue={self.companyName} required maxLength={200}/></label><button disabled={busy}>회사정보 저장</button></form><h2>회원가입 요청 및 승인 계정</h2><p>관리자 포함 최대 2개 계정을 승인할 수 있습니다. 회사코드·회사명을 확인한 후 승인해주세요.</p><table><thead><tr><th>이메일</th><th>회사코드</th><th>회사명</th><th>상태</th><th>처리</th></tr></thead><tbody>{members.map(member=><tr key={member.id}><td>{member.email}</td><td>{member.companyCode}</td><td>{member.companyName}</td><td>{labels[member.status]}</td><td>{member.role!=='admin'&&(member.status==='pending'?<><button disabled={busy} onClick={()=>act('approve',member.id)}>승인</button><button disabled={busy} onClick={()=>act('reject',member.id)}>거절</button></>:member.status==='approved'?<button disabled={busy} onClick={()=>act('suspend',member.id)}>이용 정지</button>:null)}</td></tr>)}</tbody></table></>}</main>;
}
